name: SBOM generation
on:
  workflow_dispatch
jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repo
        uses: actions/checkout@v6.0.2

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Build Maven project
        run: mvn -B clean package -DskipTest

      - name: Install Syft
        run: curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin

      - name: Building SBOM
        run: syft dir:. -o cyclonedx-json > dvja-sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v7.0.0
        with:
          name: sbom-report
          path: dvja-sbom.json
